### ISSUE TITLE
Build issue on Ubuntu 20.04  - 5.8.0-59-generic

### ISSUE THREAD

**Issue by mjsearle** [ivandavidov/minimal#236]
I had add --enable-cet to this section in 04_build_glibc.sh to get it to build.  

echo "Configuring glibc."
$GLIBC_SRC/configure \
  --prefix= \
  --with-headers=$KERNEL_INSTALLED/include \
  --without-gd \
  --without-selinux \
  --disable-werror \
  --enable-cet \
  CFLAGS="$CFLAGS"

Otherwise got "undefined reference to `_dl_cet_check'" and follow on errors. Appears to be same issue as was discussed here.
https://stackoverflow.com/questions/58995065/undefined-reference-to-dl-cet-check-while-building-glibc

**Comment by ivandavidov** [comment]
You should have no problems with the latest and greatest GCC and GLIBC, since the issue has been fixed quite a while ago. Have you tried updating and upgrading all packages? Also, instead of modifying how GLIBC is built, perhaps you'd better add the compiler flag ``-fcf-protection=none`` to ``CFLAGS`` (see [here](https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html)).

**Comment by mjsearle** [comment]
Thanks for the response.  I had done apt update and apt upgrade as per the instructions, my Ubuntu 20.04 is right up to date. Since then I have rebooted if that would make any difference. I still get the same error if try to build without using --enable-cet  . I am not expert in this but I changed CFLAGS="$CFLAGS"  to CFLAGS="-fcf-protection=none" in the above 04_build_glibc.sh as echo $CFLAGS returned an empty string in my terminal, not sure if that is how was supposed to do it, but that resulted in the same build error.
The .iso built with --enable-cet boots fine.  Overall, great project, thanks for making it available.

**Comment by ivandavidov** [comment]
Take a look at the very end of the [.config](https://github.com/ivandavidov/minimal/blob/master/src/.config#L229) file. Try to add the flag there, rebuild MLL and let me know if this resolves the issue.

**Comment by mjsearle** [comment]
Sorry for the late response. Added -fcf-protection=none  to the last line of .config and with --enable-cet commented out, get the same build error. 

`/usr/bin/ld: /home/mark/minimal_linux_live_15-Dec-2019_src/minimal_linux_live_15-Dec-2019/work/glibc/glibc_objects/elf/librtld.os: in function `_rtld_main_check':
/home/mark/minimal_linux_live_15-Dec-2019_src/minimal_linux_live_15-Dec-2019/work/glibc/glibc-2.30/elf/../sysdeps/x86/dl-prop.h:33: undefined reference to `_dl_cet_check'
/usr/bin/ld: /home/mark/minimal_linux_live_15-Dec-2019_src/minimal_linux_live_15-Dec-2019/work/glibc/glibc-2.30/elf/../sysdeps/x86/dl-prop.h:33: undefined reference to `_dl_cet_check'
/usr/bin/ld: /home/mark/minimal_linux_live_15-Dec-2019_src/minimal_linux_live_15-Dec-2019/work/glibc/glibc-2.30/elf/../sysdeps/x86/dl-prop.h:33: undefined reference to `_dl_cet_check'
/usr/bin/ld: /home/mark/minimal_linux_live_15-Dec-2019_src/minimal_linux_live_15-Dec-2019/work/glibc/glibc_objects/elf/librtld.os: in function `_dl_open_check':
/home/mark/minimal_linux_live_15-Dec-2019_src/minimal_linux_live_15-Dec-2019/work/glibc/glibc-2.30/elf/../sysdeps/x86/dl-prop.h:41: undefined reference to `_dl_cet_open_check'
/usr/bin/ld: /home/mark/minimal_linux_live_15-Dec-2019_src/minimal_linux_live_15-Dec-2019/work/glibc/glibc_objects/elf/ld.so.new: hidden symbol `_dl_cet_open_check' isn't defined
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:508: /home/mark/minimal_linux_live_15-Dec-2019_src/minimal_linux_live_15-Dec-2019/work/glibc/glibc_objects/elf/ld.so] Error 1
make[2]: Leaving directory '/home/mark/minimal_linux_live_15-Dec-2019_src/minimal_linux_live_15-Dec-2019/work/glibc/glibc-2.30/elf'
make[1]: *** [Makefile:259: elf/subdir_lib] Error 2
make[1]: Leaving directory '/home/mark/minimal_linux_live_15-Dec-2019_src/minimal_linux_live_15-Dec-2019/work/glibc/glibc-2.30'
make: *** [Makefile:9: all] Error 2
mark@mark-desktop:~/minimal_linux_live_15-Dec-2019_src/minimal_linux_live_15-Dec-2019$ cat .config | grep 'CFLAGS='
CFLAGS=-Os -s -fcf-protection=none -fno-stack-protector -fomit-frame-pointer -U_FORTIFY_SOURCE 
mark@mark-desktop:~/minimal_linux_live_15-Dec-2019_src/minimal_linux_live_15-Dec-2019$ cat 04_build_glibc.sh | grep 'enable-cet'
#  --enable-cet \
`

**Comment by thetillhoff** [comment]
Having the same issue.
In my case, I wanted to offload the building process into a docker container. Therefore perfect for reproduction.
Used the following Dockerfile:
```
FROM ubuntu

RUN apt update \
  && apt upgrade -y \
  && apt install -y \
    # dependencies for building mll:
    wget \
    make \
    gawk \
    gcc \
    bc \
    bison \
    flex \
    xorriso \
    libelf-dev \
    libssl-dev \
    # own additions (needed for building mll as well):
    xz-utils \
    rsync \
    python3 \
  && apt autoremove -y \
  && apt clean \
  # Set python3 as default - not sure if necessary
  && ln -s /usr/bin/python3 /usr/bin/python

RUN wget http://github.com/ivandavidov/minimal/releases/download/15-Dec-2019/minimal_linux_live_15-Dec-2019_src.tar.xz -O /root/mll.tar.xz \
  && tar xf /root/mll.tar.xz -C /root/ --strip 1 \
  && rm /root/mll.tar.xz

# Inserting additional parameter for building glibc. Known error, which should already be fixed in newer versions, but still seems to exist for me.
# '\ ' escapes the space character, '\\' escapes the backslash character
# This line fixes the issue:
#RUN sed -i '/^  CFLAGS="$CFLAGS"/i \ \ --enable-cet \\' /root/04_build_glibc.sh

WORKDIR /root/

CMD ["./build_minimal_linux_live.sh"]

```
